left_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: "left_wheel_joint"
  pid: {p: 0.01, i: 0.0, d: 0.0}

right_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: "right_wheel_joint"
  pid: {p: 0.01, i: 0.0, d: 0.0}

gazebo_ros_control:
  pid_gains:
    left_wheel_joint:
      p: 0.01
      i: 0.0
      d: 0.0
    right_wheel_joint:
      p: 0.01
      i: 0.0
      d: 0.0